"""initial schema

Revision ID: 1b1da95260fa
Revises: 
Create Date: 2026-06-26 00:35:31.559350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b1da95260fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicem8_api_key', sa.String(length=255), nullable=False),
    sa.Column('file_storage_path', sa.String(length=500), nullable=False),
    sa.Column('generation_buffer_days', sa.Integer(), nullable=False),
    sa.Column('last_successful_sync_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('primary_contact', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('database_backup_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('parsed_document_text', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('historical_average_labor_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('site_address', sa.Text(), nullable=False),
    sa.Column('servicem8_client_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicem8_client_uuid')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('servicem8_asset_uuid', sa.String(length=255), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicem8_asset_uuid')
    )
    op.create_table('maintenance_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('estimated_labor_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('frequency_months', sa.Integer(), nullable=False),
    sa.Column('date_last_done', sa.Date(), nullable=True),
    sa.Column('date_next_due', sa.Date(), nullable=False),
    sa.Column('permanent_custom_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('target_month_year', sa.String(length=7), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('servicem8_job_uuid', sa.String(length=255), nullable=True),
    sa.Column('customer_po_link', sa.String(length=500), nullable=True),
    sa.Column('actual_labor_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_status IN ('Waiting Approval', 'Approved', 'Refused by Customer', 'Cancelled')", name='ck_job_instances_approval_status'),
    sa.CheckConstraint("sync_status IN ('Unsynced', 'In-Progress', 'Completed', 'Bypassed')", name='ck_job_instances_sync_status'),
    sa.CheckConstraint("target_month_year ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'", name='ck_job_instances_month_year_format'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['maintenance_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicem8_job_uuid')
    )
    op.create_table('job_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_instance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('is_system_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_instance_id'], ['job_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_comments')
    op.drop_table('job_instances')
    op.drop_table('maintenance_schedules')
    op.drop_table('assets')
    op.drop_table('sites')
    op.drop_table('users')
    op.drop_table('service_templates')
    op.drop_table('database_backup_log')
    op.drop_table('customers')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
